# Generated by Django 3.2.6 on 2021-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('regdt', models.DateField(db_column='regDt')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
