# Generated by Django 3.2.6 on 2021-08-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_mail', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved')], default='1', max_length=20)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
